theme: jekyll-theme-minimal
title: The VRE
description: A comprehensive analysis platform to serve the needs of Particle Physics and Astrophysics [Science Projects](https://escape2020.pages.in2p3.fr/virtual-environment/home/).  
logo: /images/logo.png
show_downloads: true
